### ISSUE TITLE
Add CGI mode

### ISSUE THREAD

**Issue by binki** [fbbdev/node-fastcgi#10]
The C fastcgi library supports falling back to CGI when the invoker does not provide FastCGI. Currently, node-fastcgi fails with a socket error when invoked directly. It would be nice if node-fastcgi could do this same sort of fallback.

**Comment by fbbdev** [comment]
It would be nice but it's a bit out of scope for this library, whose aim is to provide a pure FastCGI server for node. I'd have to add a dependency on some CGI module, but it turns out npm is quite lacking in this area, with only a few abandoned projects.

Anyway, I added [a script](https://github.com/fbbdev/node-fastcgi/blob/master/example/cgiFallback.js) in the example directory demonstrating how to fall back to CGI. It's based on [puffnfresh/node-cgi](https://github.com/puffnfresh/node-cgi) which is not on npm.

The idea is that when the invoker is using FastCGI, fd 0 (stdin) is a socket, so you stat fd 0 and check if the socket flag is set. If not, you drop to CGI.

```js
var fs = require('fs');

if (fs.fstatSync(0).mode & fs.constants.S_IFSOCK) {
    // FastCGI
} else {
    // CGI
}
```

I think I'll deal with this in the next iteration of `node-fastcgi`.

**Comment by binki** [comment]
I know that with the current codebase it would be a big change to support CGI fallback. But with FastCGI the concept was that it’s CGI just with the variables sent using a mechanism other than the environment (`getenv()`, `setenv()`). It’d be cool if the “turn CGI variables into a node `http` module-style request object” could be shared between the implementation FastCGI and the CGI fallback.

Of course, I don’t actually need this, just seemed like it’d be nice. And as a side effect you might be able to just invoke a script directly from a terminal and get something more interesting than a stacktrace ;-).

**Comment by fbbdev** [comment]
Here's what I think I'll do: create a backend module that just parses a CGI environment and streams into a request object, then create two different frontend modules for FastCGI and plain old CGI and add a method in the FastCGI module to check if the script is being invoked as a FastCGI service.

Automatic fallback should not be the default and relative logic should not be hard-coded in the FastCGI module IMO because

  1. Most people only use FastCGI on their servers and don't need to fall back to CGI
  2. It could very easily turn into a security hole
  3. Adding features to a module unrelated to its core functionality makes integration in different systems more difficult and brings in unnecessary dependencies

If I were to add that feature I would put it behind an option and turn it off by default, but I'm more for not adding it in the first place.

**Comment by fbbdev** [comment]
If you need to test FastCGI scripts in the terminal, the `cgi-fcgi` tool allows you to do so. You can find it in the `fcgi` package on Fedora, Redhat and Arch Linux, in `libfcgi0ldbl` on Debian and derivatives. I don't know where to find a Mac or Windows version.

Say you have a script: `fcgi.js`

First you run
```sh
cgi-fcgi -start -connect /tmp/socket ./fcgi.js
```

Then for each invocation set the environment and run
```sh
cgi-fcgi -bind -connect /tmp/socket
```

When done, remember to find and kill the fastcgi service process.
```sh
kill $(ps -ef | grep fcgi.js | awk 'NR == 1{print $2}')
```
