### ISSUE TITLE
Any luck using this with ts-node? I get orphaned processes with ts-node + apache fcgid

### ISSUE THREAD

**Issue by jbcbdse** [fbbdev/node-fastcgi#19]
Have you had any luck using this with ts-node? Is there a better way to use this with typescript? I'm having an issue with orphaned processes.

Here's my wrapper

```
#!/bin/sh

NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
export NODE_PATH
cd "$(dirname "$0")"
exec node ./node_modules/.bin/ts-node ./src/server.ts
```

Here's some debug I added to my server.ts:

```
process.on("beforeExit", () => {
	console.log("Process is exiting");
});
process.on("disconnect", () => {
	console.log("Process is disconnected");
})
process.on("SIGTERM", () => {
	console.log("Received SIGTERM");
	process.abort();
});
process.on("SIGINT", () => {
	console.log("Received SIGINT");
	process.abort();
});
process.on("SIGHUP", () => {
	console.log("Received SIGHUP");
	process.abort();
});
```

And I'm using fcgid in apache like this:

```
FcgiMaxRequestsPerProcess 1
FcgiMaxRequestsPerClass 1
FcgidMaxProcessesPerClass 1
```

But I end up with orphaned processes:

```
www-data  5546     1  0 04:38 ?        00:00:00 /usr/bin/nodejs /media/data/xxx/node_modules/ts-node/dist/_bin.js ./src/server.ts
www-data  5570     1  1 04:38 ?        00:00:00 /usr/bin/nodejs /media/data/xxx/node_modules/ts-node/dist/_bin.js ./src/server.ts
www-data  5596     1  1 04:39 ?        00:00:00 /usr/bin/nodejs /media/data/xxx/node_modules/ts-node/dist/_bin.js ./src/server.ts
www-data  5620     1  1 04:39 ?        00:00:00 /usr/bin/nodejs /media/data/xxx/node_modules/ts-node/dist/_bin.js ./src/server.ts
www-data  5639  4509 33 04:48 ?        00:00:00 node ./node_modules/.bin/ts-node ./src/server.ts
www-data  5650  5639 69 04:48 ?        00:00:00 /usr/bin/nodejs /media/data/xxx/node_modules/ts-node/dist/_bin.js ./src/server.ts

```
Process 5639 is the most recent one started by Apache. When apache kills it off, the child nodejs processes are left behind.

None of those debug events fire. No "disconnect", "SIGINT", "SIGTERM", etc. Eventually, I will do `killall nodejs` and the SIGTERM events will fire. But the child nodejs process doesn't get any of those signals when the ts-node process is killed off.

I'm just curious if you've tried it yet or if you can offer any insight. Thanks!

**Comment by fbbdev** [comment]
There are many things that could be going wrong here. Basically, when a FastCGI service is started, its STDIN file descriptor (fd 0) is replaced by a bound socket (as specified [here](https://github.com/fbbdev/node-fastcgi#listening-for-connections) and [here](https://fast-cgi.github.io/spec#32-accepting-transport-connections)) and often STDOUT and STDERR streams are closed or redirected by apache.

The first and foremost effect is that **logging by `console.log` is not going to work**. If you need to debug your script you can use the FastCGI error stream (available as [a property of the socket object](https://github.com/fbbdev/node-fastcgi#the-socket-object) after a request has been received). Data written to that stream should get logged by apache. Of course this is not going to work if you can't even receive a request. That's why I'm using `fs.appendFileSync` on a custom log file [in the examples](https://github.com/fbbdev/node-fastcgi/blob/master/example/fileServer.js#L29).

The second issue is, **you need to be completely sure no process is meddling with STDIN** (fd 0, the FastCGI socket) e.g. by reading from it or replacing it with another stream. Otherwise, the socket could get in a bad state or even get completely hidden from the actual FastCGI script. It's also better to avoid any interaction with STDOUT and STDERR.

It's good you used `exec` in your wrapper in order to completely replace the shell process with the node process, but on my server this is not enough: I also need to stop other commands (like `export`, `cd` and `dirname`) from accessing STDIN and STDOUT streams – though a lot of different configurations exist and this could not be your case. This can be done by redirecting their input and output to `/dev/null`.

``` sh
#!/bin/sh

export SOMEVAR=somevalue < /dev/null > /dev/null
cd $(dirname "$0" < /dev/null) < /dev/null > /dev/null
exec node ./node_modules/.bin/ts-node ./src/server.ts
```

Note that I'm not redirecting the output stream of the `dirname` command since it's already redirected by command substitution syntax `$(...)` 😁 

Finally, and I fear that's the worst part, you need to be sure your typescript interpreter is not **ever** trying to read from STDIN or write to STDOUT/STDERR; also, when it spawns subprocesses, it should pass down correctly at least file descriptor 0 without changing it. The best thing would be to use exec and replace itself, without spawning any process. I don't even understand why on earth are they spawning a subprocess, [from what I've seen](https://github.com/TypeStrong/ts-node/blob/master/src/bin.ts) they run some argument sanitization then invoke the real interpreter 😕 

I'm not experienced with TS but if you send me a small example (maybe [the README example](https://github.com/fbbdev/node-fastcgi#example) converted to typescript) I can try to debug it. A good tool for debugging fastcgi scripts is `cgi-fastcgi` (install `libfcgi-bin` on Ubuntu, `fcgi` on Fedora, RedHat Extras and ArchLinux). You can use it to send requests to a FastCGI script with the CGI protocol.

```sh
$ cgi-fcgi -start -connect /tmp/socket ./wrapper.sh
$ REQUEST_URI=/ cgi-fcgi -bind -connect /tmp/socket
Status: 200 OK
...
```
Remember to kill all lingering node processes after testing.

**Comment by fbbdev** [comment]
UPDATE: I understand now the `ts-node` startup process, they want to ensure some specific V8 flags are passed to nodejs before starting the typescript interpreter... no easy workaround there. Let's hope that's not causing your problem 😄 (though I believe it could be fixed anyway).

**Comment by jbcbdse** [comment]
Thanks for the detailed response!

I doubt that my issue is the pipes... the same wrapper was working before I converted everything to typescript and ts-node. I can verify, though.  

I assume that their `{ stdio: 'inherit' }` part means that the descriptors are passed down correctly.

I even see the `proc.on('exit'...` like that looks like they're trying to catch any exit signals and pass them to the child process, which means my script should have caught those signals. I wonder why that's not working. Maybe I wasn't listening for the right signal? I wonder if I can manually add debug to the ts-node script.

When I give this a shot again later, I'd be glad to work up a more simplified example and give it to you. That should be simple enough. 

How does mod_fcgid kill processes when FcgidMaxProcessesPerClass or FcgiMaxRequestsPerClass is it? I figure if it was just sending SIGTERM, things would have worked. 

Thanks again. I'll let you know if I gather some more info.

**Comment by jbcbdse** [comment]
I totally read that backwards. ts-node is listening for the nodejs process to die and then responding to that, not the other way around. Oops.

**Comment by fbbdev** [comment]
I've been running some tests with ts-node and wrappers. Everything is working perfectly with `cgi-fcgi`. Now I suspect I misinterpreted your question... 😅

Your script *is* responding to requests, is that right? If this is the case, and your problem is only that child processes never quit, well, I believe what's happening is that `mod_fcgid` is killing the parent `ts-node` processes, but their children are still listening on the FastCGI socket so they become children of PID 1 and keep running indefinitely. You can try removing the `exec` command in the wrapper script, then run the ts interpreter as a background process and add a trap to kill the whole process group when the wrapper terminates (see https://stackoverflow.com/a/22644006/1154720).

```sh
#!/bin/sh

trap "exit" SIGTERM SIGINT
trap "kill 0" EXIT

NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
export NODE_PATH
cd "$(dirname "$0")"

node ./node_modules/.bin/ts-node ./src/server.ts <&0 >&1 2>&2 &
wait
```
Note I removed the `exec` command and added I/O redirection, the `&` operator and the `wait` command to keep the wrapper script alive while the interpreter runs.

**Comment by jbcbdse** [comment]
Yes, correct! The script was running and responding fine, but left orphaned child processes even after the `ts-node` process was killed by mod_fcgid. So, I would quickly run out of memory (tiny AWS instance) because I would get processes stacked up.

I will give this a shot as soon as I can. 

I appreciate the help. It seems like fcgi went through a fad a few years ago, but I can hardly find any relevant resources anymore.

**Comment by jbcbdse** [comment]
Ok, I think it's working. Here's what I have.

```
#!/bin/bash

trap "exit" TERM INT 
trap "kill -INT 0" EXIT 

NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
export NODE_PATH 
cd "$(dirname "$0")"
./node_modules/.bin/ts-node ./src/server.ts <&0 1>&1 2>&2 &
wait
```

First, note the /bin/bash. After trying every combination of `< /dev/null > /dev/null` and such that I could think of I made the wild guess that the problem could be dash, since Ubuntu defaults to dash as /bin/sh.  This worked and made progress. The redirects `<&0 1>&1 2>&2` are still necessary. Without them, I get:

```
Error: listen EINVAL
    at Object._errnoException (util.js:1041:11)
    at _exceptionWithHostPort (util.js:1064:20)
...
```

So, with that fixed, I now have a new problem. Everything was working except, I would constantly get: 

```
[Thu Dec 07 01:43:26.963447 2017] [fcgid:error] [pid 4562] mod_fcgid: fcgid process manager died, restarting the server
[Thu Dec 07 01:43:30.311997 2017] [core:warn] [pid 4562] AH00045: child process 4843 still did not exit, sending a SIGTERM
[Thu Dec 07 01:43:30.312398 2017] [core:warn] [pid 4562] AH00045: child process 4844 still did not exit, sending a SIGTERM
[Thu Dec 07 01:43:30.312558 2017] [core:warn] [pid 4562] AH00045: child process 4845 still did not exit, sending a SIGTERM
[Thu Dec 07 01:43:30.312706 2017] [core:warn] [pid 4562] AH00045: child process 4846 still did not exit, sending a SIGTERM
[Thu Dec 07 01:43:31.313961 2017] [mpm_prefork:notice] [pid 4562] AH00173: SIGHUP received.  Attempting to restart
[Thu Dec 07 01:43:31.321587 2017] [mpm_prefork:notice] [pid 4562] AH00163: Apache/2.4.18 (Ubuntu) mod_fcgid/2.3.9 configured -- resuming normal operations
[Thu Dec 07 01:43:31.321797 2017] [core:notice] [pid 4562] AH00094: Command line: '/usr/sbin/apache2'
[Thu Dec 07 01:44:47.676512 2017] [mpm_prefork:notice] [pid 4562] AH00171: Graceful restart requested, doing restart
[Thu Dec 07 01:44:47.728660 2017] [mpm_prefork:notice] [pid 4562] AH00163: Apache/2.4.18 (Ubuntu) mod_fcgid/2.3.9 configured -- resuming normal operations
[Thu Dec 07 01:44:47.728747 2017] [core:notice] [pid 4562] AH00094: Command line: '/usr/sbin/apache2'
```

I figured it was something to do with the `trap` and `kill` lines.  Again, this is deep Linux voodoo that's a little out of my area. So, note the `kill -INT 0`, so it sends SIGINT instead of the default SIGTERM to the child processes. This works. mod_fcgid no longer throws a little fit and dies.

Nothing bad in the error log. All looks good. mod_fcgid is respecting config options: it can stay open for 1 request at a time and die, or 5 requests at a time, etc.

**Comment by fbbdev** [comment]
Glad to know it's working.

> I made the wild guess that the problem could be dash

Yeah, dash is often painful. It was working with `/bin/sh` for me, but sh defaults to bash on my distro. I just did some quick tests with dash but wasn't able to fix it. It does not seem to be a syntax problem, looks like dash implements some functionality in different ways.

> The redirects <&0 1>&1 2>&2 are still necessary

Background processes are automatically redirected to `/dev/null` when the shell is not interactive, that's why you need explicit redirections.

> I figured it was something to do with the trap and kill lines. Again, this is deep Linux voodoo
> that's a little out of my area. So, note the kill -INT 0, so it sends SIGINT instead of the default
> SIGTERM to the child processes. This works. mod_fcgid no longer throws a little fit and dies.

`kill 0` is sending SIGTERM to all processes in the same process group of the wrapper script, not just children. This apparently includes `mod_fcgid`'s process manager, which luckily appears to be ignoring SIGINT. Quite a dirty hack 😄
In order to do it right, we need to run the interpreter in a separate process group, then send SIGTERM to that group only. Here's an updated version of the wrapper, I tested it with bash and it seems to be working fine.

```sh
#!/bin/bash

trap "exit" INT TERM
trap "kill -- -\$CHILD_PGID 2> /dev/null" EXIT

NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
export NODE_PATH
cd "$(dirname "$0")"

set -m
./node_modules/.bin/ts-node ./src/server.ts <&0 >&1 2>&2 &
CHILD_PGID=$!
set +m

wait
```

Note in the trap line:
  - the escaped dollar sign, so that variable substitution is not performed immediately, but when the trap is run
  - the minus sign before the PID: when given a negative argument, kill signals a group instead of a single process. The double dash separator (`--`) is needed to discriminate the negative PID from a signal specification (e.g. `-9` could be interpreted as SIGKILL)
  - stderr redirection to silence error messages (e.g. when all children have already died)

`set -m` enables job control: after that, all jobs shall be run in their own process groups (see the [POSIX man page for `set`](http://pubs.opengroup.org/onlinepubs/009696799/utilities/set.html)). The interpreter is started as a background job, then we save its PID, which is also the PGID of its separate process group (the special variable `$!` contains the PID of the most recent background command). Finally we disable job control (`set +m`) and wait. When a signal is received, the trap can signal the interpreter and all of its children (unless they ended up in a different process group, which should not be the case in normal circumstances).

**Comment by fbbdev** [comment]
Let me know if this works!

**Comment by jbcbdse** [comment]
Yes, this worked beautifully. Thanks for the clear explanation. Using this wrapper, I was able to monitor processes and they worked as expected. With `FcgidMaxRequestsPerProcess 5`, the process did not start until the first request was made. That same process ran while the next 4 requests were made, and then terminated after the 5th request was processed. The process started again upon the next request.
