### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by jbcbdse** [fbbdev/node-fastcgi#7]
Hi, I'm a little new here and didn't know the best way to contact you. 

I was having trouble getting fcgi to work with express. I saw somewhere else that you said to call fcgi.patchHttp() and that worked for me in simplified case I'm working on. Thank you!

That function isn't mentioned on the module's homepage here. Is there anything else I need to know? is there comprehensive documentation I'm missing?

**Comment by jbcbdse** [comment]
Never mind. I looked at index.js and it became bit more obvious what's going on. I see that patchHttp() is the only thing tacked on top of the existing functions. Thanks!

**Comment by fbbdev** [comment]
Hello! Issues are usually the right way to contact project maintainers on Github, unless they specified otherwise.

As you can read in #4 and the related expressjs/express#2805, express interacts destructively with anything trying to replace the http module. This is a well-known express issue.

There are two workarounds: the first one is monkey-patching the http module, which is implemented by my module and must be done strictly before the first call to `require('express')`. The downside is that this breaks any other module that may be using the http module, and monkey-patching a core nodejs module is very bad practice anyway. This is why the `patchHttp` function is undocumented.

The second method is explained in the express issue I linked above and consists in replacing the prototype of express' own request and response objects. This is the best workaround and should be preferred. I think it's not going to do any harm, since my implementation is based on the original objects in the http module.

The best way would be to rewrite my module and make it compatible with express out of the box, which I'm going to do soon since the current implementation is a total mess :smile:

Thank you for pointing out the lack of documentation, I'll add some more information in the readme.

**Comment by jbcbdse** [comment]
Thank you! It sounds like I'm on the right track. I'll try the __proto__ solution in the other thread and see how that goes. I don't think either one would be harmful to the application I'm planning on. In the end, I would make fcgi vs http a configuration option only using one or the other.

**Comment by fbbdev** [comment]
Hello. I just finished rewriting the module, it should work with express out of the box now, _without any workarounds_. Could you test the latest version from the master branch and tell me if it works for you? I think it's ready for release but I'd prefer to get some feedback before releasing a new version on npm.

**Comment by jbcbdse** [comment]
I will give this a shot tonight. Since I'm just getting started I should
have simplified test cases. I'll try the app.all/get/post functions, and
the router functions

On Thu, May 19, 2016 at 10:16 AM, Fabio Massaioli <notifications@github.com>
wrote:

> Hello. I just finished rewriting the module, it should work with express
> out of the box now, *without any workarounds*. Could you test the latest
> version from the master branch and tell me if it works for you? I think
> it's ready for release but I'd prefer to get some feedback before releasing
> a new version on npm.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/fbbdev/node-fastcgi/issues/7#issuecomment-220356680>
>



-- 
Jon Barnett

**Comment by jbcbdse** [comment]
This worked for me just fine this evening. No issues or workarounds.
`
"use strict";

// use FastCGI instead of the HTTP module
var fcgi = require('./lib/node-fastcgi');

var express = require("express");

var app = express();

app.all("/foo", function(req, res) {
        res.send("Hello world!");
});

app.get("/index.html", function(req, res) {
        res.send(req.route.path + " handled");
});

app.all("*", function(req, res) {
        res.sendStatus(404);
});

process.stdout.on("error", function(err) {
        console.error(err);
});
fcgi.createServer(app).listen();
`

**Comment by jbcbdse** [comment]
Would it be worth it to document a simplified fcgi wrapper sample? This is mine. 
```
#!/bin/sh

# env for www-data doesn't have NODE_PATH set
NODE_PATH=/usr/lib/nodejs:/usr/lib/node_modules:/usr/share/javascript
export NODE_PATH
cd "$(dirname "$0")"
exec node server.js
```

**Comment by fbbdev** [comment]
Thank you for testing it.

I don't know if a wrapper example belongs here, there is a wild variety of configurations out there. For example, on my server I don't need any wrapper and your example does not work anyway. Mine goes more like this:

```sh
#!/bin/sh

export SOMEVAR=somevalue < /dev/null > /dev/null
cd $(dirname "$0" < /dev/null) < /dev/null > /dev/null
exec node server.js
```

There is no universal example... I fear if I put one in the docs, I'd have to debug countless issues like "the wrapper is not working" :smile:

**Comment by jbcbdse** [comment]
Good point. Glad it's working!
